services:
  postgres:
    image: postgres:18
    restart: always
    container_name: BallX-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql # 18+
      #- postgres_data:/var/lib/postgresql/data
      # postgres18 이전버젼의(ex:16) 경우 위와 같이 경로를 변경
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ballx_local

  redis:
    image: redis:latest
    container_name: BallX-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: